server:
  port: ${port:8080}

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: root
  application:
    name: user-service

mybatis:
  type-aliases-package: com.hyy.user.pojo

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka,http://127.0.0.1:8083/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    # 续约间隔，默认30秒
    lease-renewal-interval-in-seconds: 5
    # 服务失效时间，默认90秒
    lease-expiration-duration-in-seconds: 5

